//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteProyecto.ServiceReference4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/ADO")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteProyecto.ServiceReference4.Puntuacion[] PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int campaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fichaCampaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int partidasJugadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteProyecto.ServiceReference4.Puntuacion[] Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntuacionField, value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int campania {
            get {
                return this.campaniaField;
            }
            set {
                if ((this.campaniaField.Equals(value) != true)) {
                    this.campaniaField = value;
                    this.RaisePropertyChanged("campania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fichaCampania {
            get {
                return this.fichaCampaniaField;
            }
            set {
                if ((this.fichaCampaniaField.Equals(value) != true)) {
                    this.fichaCampaniaField = value;
                    this.RaisePropertyChanged("fichaCampania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idioma {
            get {
                return this.idiomaField;
            }
            set {
                if ((this.idiomaField.Equals(value) != true)) {
                    this.idiomaField = value;
                    this.RaisePropertyChanged("idioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int partidasJugadas {
            get {
                return this.partidasJugadasField;
            }
            set {
                if ((this.partidasJugadasField.Equals(value) != true)) {
                    this.partidasJugadasField = value;
                    this.RaisePropertyChanged("partidasJugadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Puntuacion", Namespace="http://schemas.datacontract.org/2004/07/ADO")]
    [System.SerializableAttribute()]
    public partial class Puntuacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteProyecto.ServiceReference4.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puntuacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteProyecto.ServiceReference4.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puntuacion {
            get {
                return this.puntuacionField;
            }
            set {
                if ((this.puntuacionField.Equals(value) != true)) {
                    this.puntuacionField = value;
                    this.RaisePropertyChanged("puntuacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HostProyecto")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Casilla", Namespace="http://schemas.datacontract.org/2004/07/HostProyecto")]
    [System.SerializableAttribute()]
    public partial class Casilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CasillaDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CasillasCambiosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnaDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilaDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCasilllaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CasillaDestino {
            get {
                return this.CasillaDestinoField;
            }
            set {
                if ((this.CasillaDestinoField.Equals(value) != true)) {
                    this.CasillaDestinoField = value;
                    this.RaisePropertyChanged("CasillaDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CasillasCambios {
            get {
                return this.CasillasCambiosField;
            }
            set {
                if ((this.CasillasCambiosField.Equals(value) != true)) {
                    this.CasillasCambiosField = value;
                    this.RaisePropertyChanged("CasillasCambios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Columna {
            get {
                return this.ColumnaField;
            }
            set {
                if ((this.ColumnaField.Equals(value) != true)) {
                    this.ColumnaField = value;
                    this.RaisePropertyChanged("Columna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColumnaDestino {
            get {
                return this.ColumnaDestinoField;
            }
            set {
                if ((this.ColumnaDestinoField.Equals(value) != true)) {
                    this.ColumnaDestinoField = value;
                    this.RaisePropertyChanged("ColumnaDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fila {
            get {
                return this.FilaField;
            }
            set {
                if ((this.FilaField.Equals(value) != true)) {
                    this.FilaField = value;
                    this.RaisePropertyChanged("Fila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilaDestino {
            get {
                return this.FilaDestinoField;
            }
            set {
                if ((this.FilaDestinoField.Equals(value) != true)) {
                    this.FilaDestinoField = value;
                    this.RaisePropertyChanged("FilaDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCasillla {
            get {
                return this.NumeroCasilllaField;
            }
            set {
                if ((this.NumeroCasilllaField.Equals(value) != true)) {
                    this.NumeroCasilllaField = value;
                    this.RaisePropertyChanged("NumeroCasillla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJugador", ReplyAction="http://tempuri.org/IService1/GetJugadorResponse")]
        ClienteProyecto.ServiceReference4.Jugador GetJugador(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJugador", ReplyAction="http://tempuri.org/IService1/GetJugadorResponse")]
        System.Threading.Tasks.Task<ClienteProyecto.ServiceReference4.Jugador> GetJugadorAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ClienteProyecto.ServiceReference4.CompositeType GetDataUsingDataContract(ClienteProyecto.ServiceReference4.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClienteProyecto.ServiceReference4.CompositeType> GetDataUsingDataContractAsync(ClienteProyecto.ServiceReference4.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract1", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContract1Response")]
        ClienteProyecto.ServiceReference4.Casilla GetDataUsingDataContract1(ClienteProyecto.ServiceReference4.Casilla casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract1", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContract1Response")]
        System.Threading.Tasks.Task<ClienteProyecto.ServiceReference4.Casilla> GetDataUsingDataContract1Async(ClienteProyecto.ServiceReference4.Casilla casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarJugador", ReplyAction="http://tempuri.org/IService1/InsertarJugadorResponse")]
        int InsertarJugador(ClienteProyecto.ServiceReference4.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarJugador", ReplyAction="http://tempuri.org/IService1/InsertarJugadorResponse")]
        System.Threading.Tasks.Task<int> InsertarJugadorAsync(ClienteProyecto.ServiceReference4.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarUsuarioExistente", ReplyAction="http://tempuri.org/IService1/VerificarUsuarioExistenteResponse")]
        int VerificarUsuarioExistente(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerificarUsuarioExistente", ReplyAction="http://tempuri.org/IService1/VerificarUsuarioExistenteResponse")]
        System.Threading.Tasks.Task<int> VerificarUsuarioExistenteAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validarUsusario", ReplyAction="http://tempuri.org/IService1/validarUsusarioResponse")]
        bool validarUsusario(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validarUsusario", ReplyAction="http://tempuri.org/IService1/validarUsusarioResponse")]
        System.Threading.Tasks.Task<bool> validarUsusarioAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        int login(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<int> loginAsync(string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEstado", ReplyAction="http://tempuri.org/IService1/getEstadoResponse")]
        int getEstado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEstado", ReplyAction="http://tempuri.org/IService1/getEstadoResponse")]
        System.Threading.Tasks.Task<int> getEstadoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPuntuaciones", ReplyAction="http://tempuri.org/IService1/getPuntuacionesResponse")]
        string[] getPuntuaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPuntuaciones", ReplyAction="http://tempuri.org/IService1/getPuntuacionesResponse")]
        System.Threading.Tasks.Task<string[]> getPuntuacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuariosPuntuaciones", ReplyAction="http://tempuri.org/IService1/getUsuariosPuntuacionesResponse")]
        string[] getUsuariosPuntuaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuariosPuntuaciones", ReplyAction="http://tempuri.org/IService1/getUsuariosPuntuacionesResponse")]
        System.Threading.Tasks.Task<string[]> getUsuariosPuntuacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuarioUsuario", ReplyAction="http://tempuri.org/IService1/getUsuarioUsuarioResponse")]
        string getUsuarioUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuarioUsuario", ReplyAction="http://tempuri.org/IService1/getUsuarioUsuarioResponse")]
        System.Threading.Tasks.Task<string> getUsuarioUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCampaniaJugador", ReplyAction="http://tempuri.org/IService1/GetCampaniaJugadorResponse")]
        int GetCampaniaJugador(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCampaniaJugador", ReplyAction="http://tempuri.org/IService1/GetCampaniaJugadorResponse")]
        System.Threading.Tasks.Task<int> GetCampaniaJugadorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCampaniaJugador", ReplyAction="http://tempuri.org/IService1/SetCampaniaJugadorResponse")]
        void SetCampaniaJugador(int id, int campania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCampaniaJugador", ReplyAction="http://tempuri.org/IService1/SetCampaniaJugadorResponse")]
        System.Threading.Tasks.Task SetCampaniaJugadorAsync(int id, int campania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarMensaje", ReplyAction="http://tempuri.org/IService1/agregarMensajeResponse")]
        string[] agregarMensaje(int id, string mensaje, string[] mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarMensaje", ReplyAction="http://tempuri.org/IService1/agregarMensajeResponse")]
        System.Threading.Tasks.Task<string[]> agregarMensajeAsync(int id, string mensaje, string[] mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/enviarCodigo", ReplyAction="http://tempuri.org/IService1/enviarCodigoResponse")]
        int enviarCodigo(string codigo, string correo, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/enviarCodigo", ReplyAction="http://tempuri.org/IService1/enviarCodigoResponse")]
        System.Threading.Tasks.Task<int> enviarCodigoAsync(string codigo, string correo, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFichaJugador", ReplyAction="http://tempuri.org/IService1/getFichaJugadorResponse")]
        int getFichaJugador(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFichaJugador", ReplyAction="http://tempuri.org/IService1/getFichaJugadorResponse")]
        System.Threading.Tasks.Task<int> getFichaJugadorAsync(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setOpciones", ReplyAction="http://tempuri.org/IService1/setOpcionesResponse")]
        int setOpciones(int idJugador, int idioma, int ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setOpciones", ReplyAction="http://tempuri.org/IService1/setOpcionesResponse")]
        System.Threading.Tasks.Task<int> setOpcionesAsync(int idJugador, int idioma, int ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getIdiomaJugador", ReplyAction="http://tempuri.org/IService1/getIdiomaJugadorResponse")]
        int getIdiomaJugador(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getIdiomaJugador", ReplyAction="http://tempuri.org/IService1/getIdiomaJugadorResponse")]
        System.Threading.Tasks.Task<int> getIdiomaJugadorAsync(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarPuntuacionVictoria", ReplyAction="http://tempuri.org/IService1/agregarPuntuacionVictoriaResponse")]
        int agregarPuntuacionVictoria(int idJugador, int turnos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/agregarPuntuacionVictoria", ReplyAction="http://tempuri.org/IService1/agregarPuntuacionVictoriaResponse")]
        System.Threading.Tasks.Task<int> agregarPuntuacionVictoriaAsync(int idJugador, int turnos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClienteProyecto.ServiceReference4.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClienteProyecto.ServiceReference4.IService1>, ClienteProyecto.ServiceReference4.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteProyecto.ServiceReference4.Jugador GetJugador(int value) {
            return base.Channel.GetJugador(value);
        }
        
        public System.Threading.Tasks.Task<ClienteProyecto.ServiceReference4.Jugador> GetJugadorAsync(int value) {
            return base.Channel.GetJugadorAsync(value);
        }
        
        public ClienteProyecto.ServiceReference4.CompositeType GetDataUsingDataContract(ClienteProyecto.ServiceReference4.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClienteProyecto.ServiceReference4.CompositeType> GetDataUsingDataContractAsync(ClienteProyecto.ServiceReference4.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ClienteProyecto.ServiceReference4.Casilla GetDataUsingDataContract1(ClienteProyecto.ServiceReference4.Casilla casilla) {
            return base.Channel.GetDataUsingDataContract1(casilla);
        }
        
        public System.Threading.Tasks.Task<ClienteProyecto.ServiceReference4.Casilla> GetDataUsingDataContract1Async(ClienteProyecto.ServiceReference4.Casilla casilla) {
            return base.Channel.GetDataUsingDataContract1Async(casilla);
        }
        
        public int InsertarJugador(ClienteProyecto.ServiceReference4.Jugador jugador) {
            return base.Channel.InsertarJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<int> InsertarJugadorAsync(ClienteProyecto.ServiceReference4.Jugador jugador) {
            return base.Channel.InsertarJugadorAsync(jugador);
        }
        
        public int VerificarUsuarioExistente(string usuario) {
            return base.Channel.VerificarUsuarioExistente(usuario);
        }
        
        public System.Threading.Tasks.Task<int> VerificarUsuarioExistenteAsync(string usuario) {
            return base.Channel.VerificarUsuarioExistenteAsync(usuario);
        }
        
        public bool validarUsusario(string codigo) {
            return base.Channel.validarUsusario(codigo);
        }
        
        public System.Threading.Tasks.Task<bool> validarUsusarioAsync(string codigo) {
            return base.Channel.validarUsusarioAsync(codigo);
        }
        
        public int login(string usuario, string contrasenia) {
            return base.Channel.login(usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<int> loginAsync(string usuario, string contrasenia) {
            return base.Channel.loginAsync(usuario, contrasenia);
        }
        
        public int getEstado(int id) {
            return base.Channel.getEstado(id);
        }
        
        public System.Threading.Tasks.Task<int> getEstadoAsync(int id) {
            return base.Channel.getEstadoAsync(id);
        }
        
        public string[] getPuntuaciones() {
            return base.Channel.getPuntuaciones();
        }
        
        public System.Threading.Tasks.Task<string[]> getPuntuacionesAsync() {
            return base.Channel.getPuntuacionesAsync();
        }
        
        public string[] getUsuariosPuntuaciones() {
            return base.Channel.getUsuariosPuntuaciones();
        }
        
        public System.Threading.Tasks.Task<string[]> getUsuariosPuntuacionesAsync() {
            return base.Channel.getUsuariosPuntuacionesAsync();
        }
        
        public string getUsuarioUsuario(int id) {
            return base.Channel.getUsuarioUsuario(id);
        }
        
        public System.Threading.Tasks.Task<string> getUsuarioUsuarioAsync(int id) {
            return base.Channel.getUsuarioUsuarioAsync(id);
        }
        
        public int GetCampaniaJugador(int id) {
            return base.Channel.GetCampaniaJugador(id);
        }
        
        public System.Threading.Tasks.Task<int> GetCampaniaJugadorAsync(int id) {
            return base.Channel.GetCampaniaJugadorAsync(id);
        }
        
        public void SetCampaniaJugador(int id, int campania) {
            base.Channel.SetCampaniaJugador(id, campania);
        }
        
        public System.Threading.Tasks.Task SetCampaniaJugadorAsync(int id, int campania) {
            return base.Channel.SetCampaniaJugadorAsync(id, campania);
        }
        
        public string[] agregarMensaje(int id, string mensaje, string[] mensajes) {
            return base.Channel.agregarMensaje(id, mensaje, mensajes);
        }
        
        public System.Threading.Tasks.Task<string[]> agregarMensajeAsync(int id, string mensaje, string[] mensajes) {
            return base.Channel.agregarMensajeAsync(id, mensaje, mensajes);
        }
        
        public int enviarCodigo(string codigo, string correo, string asunto, string mensaje) {
            return base.Channel.enviarCodigo(codigo, correo, asunto, mensaje);
        }
        
        public System.Threading.Tasks.Task<int> enviarCodigoAsync(string codigo, string correo, string asunto, string mensaje) {
            return base.Channel.enviarCodigoAsync(codigo, correo, asunto, mensaje);
        }
        
        public int getFichaJugador(int idJugador) {
            return base.Channel.getFichaJugador(idJugador);
        }
        
        public System.Threading.Tasks.Task<int> getFichaJugadorAsync(int idJugador) {
            return base.Channel.getFichaJugadorAsync(idJugador);
        }
        
        public int setOpciones(int idJugador, int idioma, int ficha) {
            return base.Channel.setOpciones(idJugador, idioma, ficha);
        }
        
        public System.Threading.Tasks.Task<int> setOpcionesAsync(int idJugador, int idioma, int ficha) {
            return base.Channel.setOpcionesAsync(idJugador, idioma, ficha);
        }
        
        public int getIdiomaJugador(int idJugador) {
            return base.Channel.getIdiomaJugador(idJugador);
        }
        
        public System.Threading.Tasks.Task<int> getIdiomaJugadorAsync(int idJugador) {
            return base.Channel.getIdiomaJugadorAsync(idJugador);
        }
        
        public int agregarPuntuacionVictoria(int idJugador, int turnos) {
            return base.Channel.agregarPuntuacionVictoria(idJugador, turnos);
        }
        
        public System.Threading.Tasks.Task<int> agregarPuntuacionVictoriaAsync(int idJugador, int turnos) {
            return base.Channel.agregarPuntuacionVictoriaAsync(idJugador, turnos);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IChat", CallbackContract=typeof(ClienteProyecto.ServiceReference4.IChatCallback))]
    public interface IChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/unirse", ReplyAction="http://tempuri.org/IChat/unirseResponse")]
        int unirse(string usuario, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/unirse", ReplyAction="http://tempuri.org/IChat/unirseResponse")]
        System.Threading.Tasks.Task<int> unirseAsync(string usuario, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/enviarMensaje")]
        void enviarMensaje(string mensaje, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/enviarMensaje")]
        System.Threading.Tasks.Task enviarMensajeAsync(string mensaje, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/enviarMensajeJuego")]
        void enviarMensajeJuego(string mensaje, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/enviarMensajeJuego")]
        System.Threading.Tasks.Task enviarMensajeJuegoAsync(string mensaje, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/unirseUsuario")]
        void unirseUsuario(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/unirseUsuario")]
        System.Threading.Tasks.Task unirseUsuarioAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/salir")]
        void salir(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/salir")]
        System.Threading.Tasks.Task salirAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/crearPartida")]
        void crearPartida(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/crearPartida")]
        System.Threading.Tasks.Task crearPartidaAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getPartidas", ReplyAction="http://tempuri.org/IChat/getPartidasResponse")]
        string[] getPartidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getPartidas", ReplyAction="http://tempuri.org/IChat/getPartidasResponse")]
        System.Threading.Tasks.Task<string[]> getPartidasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getPartidasClave", ReplyAction="http://tempuri.org/IChat/getPartidasClaveResponse")]
        string[] getPartidasClave();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getPartidasClave", ReplyAction="http://tempuri.org/IChat/getPartidasClaveResponse")]
        System.Threading.Tasks.Task<string[]> getPartidasClaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getNumeroJugador", ReplyAction="http://tempuri.org/IChat/getNumeroJugadorResponse")]
        int getNumeroJugador(string usuario, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getNumeroJugador", ReplyAction="http://tempuri.org/IChat/getNumeroJugadorResponse")]
        System.Threading.Tasks.Task<int> getNumeroJugadorAsync(string usuario, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/entrarJuego")]
        void entrarJuego(string nombre, int tablero, int muerteSubita);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/entrarJuego")]
        System.Threading.Tasks.Task entrarJuegoAsync(string nombre, int tablero, int muerteSubita);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pintadDado")]
        void pintadDado(int tiro, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pintadDado")]
        System.Threading.Tasks.Task pintadDadoAsync(int tiro, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pintarMovimiento1")]
        void pintarMovimiento1(int columna, int fila, string nombre, int numeroEntrada);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pintarMovimiento1")]
        System.Threading.Tasks.Task pintarMovimiento1Async(int columna, int fila, string nombre, int numeroEntrada);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pasarTurno")]
        void pasarTurno(int jugador, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pasarTurno")]
        System.Threading.Tasks.Task pasarTurnoAsync(int jugador, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/moverDragones")]
        void moverDragones(int estado, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/moverDragones")]
        System.Threading.Tasks.Task moverDragonesAsync(int estado, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ganoJugador")]
        void ganoJugador(string jugador, string partida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ganoJugador")]
        System.Threading.Tasks.Task ganoJugadorAsync(string jugador, string partida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/salirJuego")]
        void salirJuego(int idJugador, string partida, int numeroEntrada);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/salirJuego")]
        System.Threading.Tasks.Task salirJuegoAsync(int idJugador, string partida, int numeroEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getNuevoNumeroJugador", ReplyAction="http://tempuri.org/IChat/getNuevoNumeroJugadorResponse")]
        int getNuevoNumeroJugador(string usuario, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/getNuevoNumeroJugador", ReplyAction="http://tempuri.org/IChat/getNuevoNumeroJugadorResponse")]
        System.Threading.Tasks.Task<int> getNuevoNumeroJugadorAsync(string usuario, string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveMensaje")]
        void ResiveMensaje(string usuario, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveUsuario")]
        void ResiveUsuario(string[] lista);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveSalida")]
        void ResiveSalida(int numero);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveMensajeJuego")]
        void ResiveMensajeJuego(string usuario, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveUsuarioJuego")]
        void ResiveUsuarioJuego(string[] lista);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveSalidaJuego")]
        void ResiveSalidaJuego(int numero);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveSalidaJuegoAbandona")]
        void ResiveSalidaJuegoAbandona();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveEntradaMulti")]
        void ResiveEntradaMulti(int i, int tablero, int muerteSubita);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pintarDado")]
        void pintarDado(int tiro);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pintarMovimiento")]
        void pintarMovimiento(int columna, int fila, int jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/pasarTurno1")]
        void pasarTurno1();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/quitarTurno")]
        void quitarTurno();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/moverDragones1")]
        void moverDragones1(int estado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ganoJugador1")]
        void ganoJugador1(string Jugador, int numeroJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveSalidaJuegoLobby")]
        void ResiveSalidaJuegoLobby(int i);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/ResiveSalidaJuegoAbandonaLobby")]
        void ResiveSalidaJuegoAbandonaLobby();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatChannel : ClienteProyecto.ServiceReference4.IChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatClient : System.ServiceModel.DuplexClientBase<ClienteProyecto.ServiceReference4.IChat>, ClienteProyecto.ServiceReference4.IChat {
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int unirse(string usuario, string nombre) {
            return base.Channel.unirse(usuario, nombre);
        }
        
        public System.Threading.Tasks.Task<int> unirseAsync(string usuario, string nombre) {
            return base.Channel.unirseAsync(usuario, nombre);
        }
        
        public void enviarMensaje(string mensaje, string nombre) {
            base.Channel.enviarMensaje(mensaje, nombre);
        }
        
        public System.Threading.Tasks.Task enviarMensajeAsync(string mensaje, string nombre) {
            return base.Channel.enviarMensajeAsync(mensaje, nombre);
        }
        
        public void enviarMensajeJuego(string mensaje, string nombre) {
            base.Channel.enviarMensajeJuego(mensaje, nombre);
        }
        
        public System.Threading.Tasks.Task enviarMensajeJuegoAsync(string mensaje, string nombre) {
            return base.Channel.enviarMensajeJuegoAsync(mensaje, nombre);
        }
        
        public void unirseUsuario(string nombre) {
            base.Channel.unirseUsuario(nombre);
        }
        
        public System.Threading.Tasks.Task unirseUsuarioAsync(string nombre) {
            return base.Channel.unirseUsuarioAsync(nombre);
        }
        
        public void salir(string nombre) {
            base.Channel.salir(nombre);
        }
        
        public System.Threading.Tasks.Task salirAsync(string nombre) {
            return base.Channel.salirAsync(nombre);
        }
        
        public void crearPartida(string nombre) {
            base.Channel.crearPartida(nombre);
        }
        
        public System.Threading.Tasks.Task crearPartidaAsync(string nombre) {
            return base.Channel.crearPartidaAsync(nombre);
        }
        
        public string[] getPartidas() {
            return base.Channel.getPartidas();
        }
        
        public System.Threading.Tasks.Task<string[]> getPartidasAsync() {
            return base.Channel.getPartidasAsync();
        }
        
        public string[] getPartidasClave() {
            return base.Channel.getPartidasClave();
        }
        
        public System.Threading.Tasks.Task<string[]> getPartidasClaveAsync() {
            return base.Channel.getPartidasClaveAsync();
        }
        
        public int getNumeroJugador(string usuario, string nombre) {
            return base.Channel.getNumeroJugador(usuario, nombre);
        }
        
        public System.Threading.Tasks.Task<int> getNumeroJugadorAsync(string usuario, string nombre) {
            return base.Channel.getNumeroJugadorAsync(usuario, nombre);
        }
        
        public void entrarJuego(string nombre, int tablero, int muerteSubita) {
            base.Channel.entrarJuego(nombre, tablero, muerteSubita);
        }
        
        public System.Threading.Tasks.Task entrarJuegoAsync(string nombre, int tablero, int muerteSubita) {
            return base.Channel.entrarJuegoAsync(nombre, tablero, muerteSubita);
        }
        
        public void pintadDado(int tiro, string nombre) {
            base.Channel.pintadDado(tiro, nombre);
        }
        
        public System.Threading.Tasks.Task pintadDadoAsync(int tiro, string nombre) {
            return base.Channel.pintadDadoAsync(tiro, nombre);
        }
        
        public void pintarMovimiento1(int columna, int fila, string nombre, int numeroEntrada) {
            base.Channel.pintarMovimiento1(columna, fila, nombre, numeroEntrada);
        }
        
        public System.Threading.Tasks.Task pintarMovimiento1Async(int columna, int fila, string nombre, int numeroEntrada) {
            return base.Channel.pintarMovimiento1Async(columna, fila, nombre, numeroEntrada);
        }
        
        public void pasarTurno(int jugador, string nombre) {
            base.Channel.pasarTurno(jugador, nombre);
        }
        
        public System.Threading.Tasks.Task pasarTurnoAsync(int jugador, string nombre) {
            return base.Channel.pasarTurnoAsync(jugador, nombre);
        }
        
        public void moverDragones(int estado, string nombre) {
            base.Channel.moverDragones(estado, nombre);
        }
        
        public System.Threading.Tasks.Task moverDragonesAsync(int estado, string nombre) {
            return base.Channel.moverDragonesAsync(estado, nombre);
        }
        
        public void ganoJugador(string jugador, string partida) {
            base.Channel.ganoJugador(jugador, partida);
        }
        
        public System.Threading.Tasks.Task ganoJugadorAsync(string jugador, string partida) {
            return base.Channel.ganoJugadorAsync(jugador, partida);
        }
        
        public void salirJuego(int idJugador, string partida, int numeroEntrada) {
            base.Channel.salirJuego(idJugador, partida, numeroEntrada);
        }
        
        public System.Threading.Tasks.Task salirJuegoAsync(int idJugador, string partida, int numeroEntrada) {
            return base.Channel.salirJuegoAsync(idJugador, partida, numeroEntrada);
        }
        
        public int getNuevoNumeroJugador(string usuario, string nombre) {
            return base.Channel.getNuevoNumeroJugador(usuario, nombre);
        }
        
        public System.Threading.Tasks.Task<int> getNuevoNumeroJugadorAsync(string usuario, string nombre) {
            return base.Channel.getNuevoNumeroJugadorAsync(usuario, nombre);
        }
    }
}
