//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteProyecto.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteProyecto.Properties.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string buttonAceptar {
            get {
                return ResourceManager.GetString("buttonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string buttonAcercaDe {
            get {
                return ResourceManager.GetString("buttonAcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campaña.
        /// </summary>
        public static string buttonCampania {
            get {
                return ResourceManager.GetString("buttonCampania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string buttonCancelar {
            get {
                return ResourceManager.GetString("buttonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar campaña.
        /// </summary>
        public static string buttonContinuar {
            get {
                return ResourceManager.GetString("buttonContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Partida.
        /// </summary>
        public static string buttonCrearPartida {
            get {
                return ResourceManager.GetString("buttonCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string buttonEnviar {
            get {
                return ResourceManager.GetString("buttonEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string buttonGuardar {
            get {
                return ResourceManager.GetString("buttonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar juego.
        /// </summary>
        public static string buttonIniciarJuego {
            get {
                return ResourceManager.GetString("buttonIniciarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string buttonIniciarSesion {
            get {
                return ResourceManager.GetString("buttonIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar contraseña.
        /// </summary>
        public static string buttonMostrarContrasena {
            get {
                return ResourceManager.GetString("buttonMostrarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multijugador.
        /// </summary>
        public static string buttonMultijugador {
            get {
                return ResourceManager.GetString("buttonMultijugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva campaña.
        /// </summary>
        public static string buttonNueva {
            get {
                return ResourceManager.GetString("buttonNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string buttonOpciones {
            get {
                return ResourceManager.GetString("buttonOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores Puntuaciones.
        /// </summary>
        public static string buttonPuntuaciones {
            get {
                return ResourceManager.GetString("buttonPuntuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string buttonRegistrar {
            get {
                return ResourceManager.GetString("buttonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string buttonRegresar {
            get {
                return ResourceManager.GetString("buttonRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string buttonSalir {
            get {
                return ResourceManager.GetString("buttonSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tirar.
        /// </summary>
        public static string buttonTirar {
            get {
                return ResourceManager.GetString("buttonTirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string buttonUnirse {
            get {
                return ResourceManager.GetString("buttonUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valida tu cuenta.
        /// </summary>
        public static string buttonValidar {
            get {
                return ResourceManager.GetString("buttonValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string labelAnterior {
            get {
                return ResourceManager.GetString("labelAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat de juego:.
        /// </summary>
        public static string labelChat {
            get {
                return ResourceManager.GetString("labelChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de verificacion.
        /// </summary>
        public static string labelCodigoVerificacion {
            get {
                return ResourceManager.GetString("labelCodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string labelContrasena {
            get {
                return ResourceManager.GetString("labelContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string labelCorreo {
            get {
                return ResourceManager.GetString("labelCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Partida.
        /// </summary>
        public static string labelCrearPartida {
            get {
                return ResourceManager.GetString("labelCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando al líder de la partida.
        /// </summary>
        public static string labelEspera {
            get {
                return ResourceManager.GetString("labelEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando Jugadores....
        /// </summary>
        public static string labelEsperandoJugadores {
            get {
                return ResourceManager.GetString("labelEsperandoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hace poco tiempo, los diferentes dictadores del tiempo se juntaron para gobernar todo el espacio tiempo, solo tu puedes detenerlo viajando en el tiempo y deteniendolos en su epoca.
        /// </summary>
        public static string labelExplicacion1 {
            get {
                return ResourceManager.GetString("labelExplicacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tu primer objetivo se encuentra en una civilizacion perdida hace 73 millones de años, Wart, lider de la civilizacion, derrotalo y obten su poder.
        /// </summary>
        public static string labelExplicacion2 {
            get {
                return ResourceManager.GetString("labelExplicacion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu siguiente objetivo es el emperador calus, del año 200, derrotalo para obtener el poder de viajar a la siguiente ubicacion.
        /// </summary>
        public static string labelExplicacion3 {
            get {
                return ResourceManager.GetString("labelExplicacion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un ficha para el modo campaña.
        /// </summary>
        public static string labelFicha {
            get {
                return ResourceManager.GetString("labelFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un fondo.
        /// </summary>
        public static string labelFondo {
            get {
                return ResourceManager.GetString("labelFondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string labelIdioma {
            get {
                return ResourceManager.GetString("labelIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string labelJugadores {
            get {
                return ResourceManager.GetString("labelJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores:.
        /// </summary>
        public static string labelJugadoresActuales {
            get {
                return ResourceManager.GetString("labelJugadoresActuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de turnos para muerte súbita.
        /// </summary>
        public static string labelMuerteSubita {
            get {
                return ResourceManager.GetString("labelMuerteSubita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la partida: .
        /// </summary>
        public static string labelNombrePartida {
            get {
                return ResourceManager.GetString("labelNombrePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es el turno de.
        /// </summary>
        public static string labelNoTurno {
            get {
                return ResourceManager.GetString("labelNoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oponente.
        /// </summary>
        public static string labelOponente {
            get {
                return ResourceManager.GetString("labelOponente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas: .
        /// </summary>
        public static string labelPartidas {
            get {
                return ResourceManager.GetString("labelPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string labelRegistrar {
            get {
                return ResourceManager.GetString("labelRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes una cuenta? Registrate.
        /// </summary>
        public static string labelRegistro {
            get {
                return ResourceManager.GetString("labelRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo 5 caracteres, Máximo  15.
        /// </summary>
        public static string labelRestriccionContrasena {
            get {
                return ResourceManager.GetString("labelRestriccionContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplo: correo@gmail.com, no mayor a 50 caracteres.
        /// </summary>
        public static string labelRestriccionEmail {
            get {
                return ResourceManager.GetString("labelRestriccionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo 1 caracteres, Máximo  50.
        /// </summary>
        public static string labelRestriccionNombre {
            get {
                return ResourceManager.GetString("labelRestriccionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo 3 caracteres, Máximo  15.
        /// </summary>
        public static string labelRestriccionusuario {
            get {
                return ResourceManager.GetString("labelRestriccionusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un tablero.
        /// </summary>
        public static string labelSeleccion {
            get {
                return ResourceManager.GetString("labelSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string labelSiguiente {
            get {
                return ResourceManager.GetString("labelSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero actual.
        /// </summary>
        public static string labelTablero {
            get {
                return ResourceManager.GetString("labelTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas ganadas mas rapido.
        /// </summary>
        public static string labelTituloPuntuaciones {
            get {
                return ResourceManager.GetString("labelTituloPuntuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu.
        /// </summary>
        public static string labelTu {
            get {
                return ResourceManager.GetString("labelTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta es tu ficha.
        /// </summary>
        public static string labelTuFicha {
            get {
                return ResourceManager.GetString("labelTuFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es tu turno.
        /// </summary>
        public static string labelTurno {
            get {
                return ResourceManager.GetString("labelTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string labelUsuario {
            get {
                return ResourceManager.GetString("labelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se te envio un codigo de verificacion a tu correo electronico, escribelo aqui.
        /// </summary>
        public static string labelVerificacion {
            get {
                return ResourceManager.GetString("labelVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique su cuenta.
        /// </summary>
        public static string StringAsunto {
            get {
                return ResourceManager.GetString("StringAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por usar Serpientes Escaleras y Dragones
        ///para poder usar su cuenta introduzca el codigo siguiente en la ventana de verificacion
        ///Codigo: .
        /// </summary>
        public static string StringMensaje {
            get {
                return ResourceManager.GetString("StringMensaje", resourceCulture);
            }
        }
    }
}
