//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteProyecto.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteProyecto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acept.
        /// </summary>
        public static string buttonAceptar {
            get {
                return ResourceManager.GetString("buttonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string buttonAcercaDe {
            get {
                return ResourceManager.GetString("buttonAcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campaign.
        /// </summary>
        public static string buttonCampania {
            get {
                return ResourceManager.GetString("buttonCampania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string buttonCancelar {
            get {
                return ResourceManager.GetString("buttonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue campaign.
        /// </summary>
        public static string buttonContinuar {
            get {
                return ResourceManager.GetString("buttonContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        public static string buttonCrearPartida {
            get {
                return ResourceManager.GetString("buttonCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string buttonEnviar {
            get {
                return ResourceManager.GetString("buttonEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string buttonGuardar {
            get {
                return ResourceManager.GetString("buttonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string buttonInfo {
            get {
                return ResourceManager.GetString("buttonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string buttonIniciarJuego {
            get {
                return ResourceManager.GetString("buttonIniciarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string buttonIniciarSesion {
            get {
                return ResourceManager.GetString("buttonIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show password.
        /// </summary>
        public static string buttonMostrarContrasena {
            get {
                return ResourceManager.GetString("buttonMostrarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplayer.
        /// </summary>
        public static string buttonMultijugador {
            get {
                return ResourceManager.GetString("buttonMultijugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New campaign.
        /// </summary>
        public static string buttonNueva {
            get {
                return ResourceManager.GetString("buttonNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string buttonOpciones {
            get {
                return ResourceManager.GetString("buttonOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top scores.
        /// </summary>
        public static string buttonPuntuaciones {
            get {
                return ResourceManager.GetString("buttonPuntuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string buttonRegistrar {
            get {
                return ResourceManager.GetString("buttonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string buttonRegresar {
            get {
                return ResourceManager.GetString("buttonRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string buttonSalir {
            get {
                return ResourceManager.GetString("buttonSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roll dice.
        /// </summary>
        public static string buttonTirar {
            get {
                return ResourceManager.GetString("buttonTirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string buttonUnirse {
            get {
                return ResourceManager.GetString("buttonUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate your account.
        /// </summary>
        public static string buttonValidar {
            get {
                return ResourceManager.GetString("buttonValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        public static string labelAnterior {
            get {
                return ResourceManager.GetString("labelAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Chat:.
        /// </summary>
        public static string labelChat {
            get {
                return ResourceManager.GetString("labelChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code:.
        /// </summary>
        public static string labelCodigo {
            get {
                return ResourceManager.GetString("labelCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a verification code.
        /// </summary>
        public static string labelCodigoVerificacion {
            get {
                return ResourceManager.GetString("labelCodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string labelContrasena {
            get {
                return ResourceManager.GetString("labelContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        public static string labelCorreo {
            get {
                return ResourceManager.GetString("labelCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        public static string labelCrearPartida {
            get {
                return ResourceManager.GetString("labelCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for the leader of the game.
        /// </summary>
        public static string labelEspera {
            get {
                return ResourceManager.GetString("labelEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wating for players....
        /// </summary>
        public static string labelEsperandoJugadores {
            get {
                return ResourceManager.GetString("labelEsperandoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a short time ago, the different dictators of time got together to rule all the timespace, only you can stop it traveling in time
        ///and stopping them in their time.
        /// </summary>
        public static string labelExplicacion1 {
            get {
                return ResourceManager.GetString("labelExplicacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your first target is in a lost civilization 73 million years ago, Wart, leader of civilization, defeat him and get his power.
        /// </summary>
        public static string labelExplicacion2 {
            get {
                return ResourceManager.GetString("labelExplicacion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your next target is Emperor Calus, from the year 200, defeat him to get the power to travel to the next location.
        /// </summary>
        public static string labelExplicacion3 {
            get {
                return ResourceManager.GetString("labelExplicacion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a tab for campaign mode.
        /// </summary>
        public static string labelFicha {
            get {
                return ResourceManager.GetString("labelFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a background.
        /// </summary>
        public static string labelFondo {
            get {
                return ResourceManager.GetString("labelFondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languaje.
        /// </summary>
        public static string labelIdioma {
            get {
                return ResourceManager.GetString("labelIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string labelJugadores {
            get {
                return ResourceManager.GetString("labelJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players:.
        /// </summary>
        public static string labelJugadoresActuales {
            get {
                return ResourceManager.GetString("labelJugadoresActuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of shifts for sudden death.
        /// </summary>
        public static string labelMuerteSubita {
            get {
                return ResourceManager.GetString("labelMuerteSubita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Name.
        /// </summary>
        public static string labelNombrePartida {
            get {
                return ResourceManager.GetString("labelNombrePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It´s turn of.
        /// </summary>
        public static string labelNoTurno {
            get {
                return ResourceManager.GetString("labelNoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oponent.
        /// </summary>
        public static string labelOponente {
            get {
                return ResourceManager.GetString("labelOponente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games:.
        /// </summary>
        public static string labelPartidas {
            get {
                return ResourceManager.GetString("labelPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration.
        /// </summary>
        public static string labelRegistrar {
            get {
                return ResourceManager.GetString("labelRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have an account?.
        /// </summary>
        public static string labelRegistro {
            get {
                return ResourceManager.GetString("labelRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum 5 characters, Maximum 15.
        /// </summary>
        public static string labelRestriccionContrasena {
            get {
                return ResourceManager.GetString("labelRestriccionContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example: mail@gmail.com, no more than 50 characters.
        /// </summary>
        public static string labelRestriccionEmail {
            get {
                return ResourceManager.GetString("labelRestriccionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum 1 characters, Maximum 50.
        /// </summary>
        public static string labelRestriccionNombre {
            get {
                return ResourceManager.GetString("labelRestriccionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum 3 characters, Maximum 15.
        /// </summary>
        public static string labelRestriccionUsuario {
            get {
                return ResourceManager.GetString("labelRestriccionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a board.
        /// </summary>
        public static string labelSeleccion {
            get {
                return ResourceManager.GetString("labelSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string labelSiguiente {
            get {
                return ResourceManager.GetString("labelSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actual board.
        /// </summary>
        public static string labelTablero {
            get {
                return ResourceManager.GetString("labelTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games won faster.
        /// </summary>
        public static string labelTituloPuntuaciones {
            get {
                return ResourceManager.GetString("labelTituloPuntuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You.
        /// </summary>
        public static string labelTu {
            get {
                return ResourceManager.GetString("labelTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is your tab.
        /// </summary>
        public static string labelTuFicha {
            get {
                return ResourceManager.GetString("labelTuFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It´s your turn.
        /// </summary>
        public static string labelTurno {
            get {
                return ResourceManager.GetString("labelTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string labelUsuario {
            get {
                return ResourceManager.GetString("labelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A verification code was sent to your email, write it here.
        /// </summary>
        public static string labelVerificacion {
            get {
                return ResourceManager.GetString("labelVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify your account.
        /// </summary>
        public static string StringAsunto {
            get {
                return ResourceManager.GetString("StringAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks for using Snakes Stairs and Dragons
        ///to use your account enter the following code in the verification window
        ///Code:.
        /// </summary>
        public static string StringMensaje {
            get {
                return ResourceManager.GetString("StringMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game.
        /// </summary>
        public static string windowCampaña {
            get {
                return ResourceManager.GetString("windowCampaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string windowInicioSesion {
            get {
                return ResourceManager.GetString("windowInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main menu.
        /// </summary>
        public static string windowMenuPrincipal {
            get {
                return ResourceManager.GetString("windowMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registry.
        /// </summary>
        public static string windowRegistro {
            get {
                return ResourceManager.GetString("windowRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate.
        /// </summary>
        public static string windowVerificar {
            get {
                return ResourceManager.GetString("windowVerificar", resourceCulture);
            }
        }
    }
}
